let dados = [
    {
        titulo: 'Breaking Bad',
        descricao: 'Um professor de química com câncer terminal, Walter White, inicia uma vida dupla no mundo do crime, produzindo e vendendo metanfetamina para garantir o futuro financeiro de sua família. A série acompanha sua transformação gradual em um poderoso chefão do tráfico, explorando temas como moralidade, ambição e as consequências de suas escolhas.',
        genero: ['Suspense', 'Drama', 'Crime'],
        streaming: 'Netflix',
        temporadas: 5,
        exibicao: '2008-2013',
        recomended1: 'Better Call Saul',
        recomended2: 'Game of Thrones',
        recomended3: 'Sucession',
    },
    {
        titulo: 'Game of Thrones',
        descricao: 'Ambientada em um mundo de fantasia medieval, Game of Thrones narra a história de várias famílias nobres que lutam pelo controle do Trono de Ferro e do reino dos Sete Reinos. A série explora temas como política, traição, amor e morte em um universo repleto de dragões, zumbis e criaturas mágicas.',
        genero: ['Fantasia', 'Drama', 'Aventura'],
        streaming: 'HBO Max',
        temporadas: 8,
        exibicao: '2011-2019',
        recomended1: 'The Lord of the Rings: The Rings of Power',
        recomended2: 'Vikings',
        recomended3: 'House of the Dragon',
    },
    {
        titulo: 'Chernobyl',
        descricao: 'Minissérie que retrata o desastre nuclear de Chernobyl, ocorrido em 1986 na Ucrânia. A série explora as causas do acidente, as tentativas de contenção e as consequências para os trabalhadores, bombeiros e população local. Chernobyl é um drama realista e emocionante que destaca a importância da verdade e da responsabilidade.',
        genero: ['Drama', 'História', 'Ficção Científica'],
        streaming: 'HBO Max',
        temporadas: 1,
        exibicao: '2019',
        recomended1: 'The Knick',
        recomended2: 'Mare of Easttown',
        recomended3: 'Fukushima: A Nuclear Story',
    },
    {
        titulo: 'The Sopranos',
        descricao: 'Drama criminal que acompanha a vida de Tony Soprano, um mafioso ítalo-americano de Nova Jersey. A série explora a psicologia de um gângster, suas relações familiares e as tensões entre sua vida pessoal e profissional. The Sopranos é considerada uma das séries mais influentes da televisão, com um roteiro complexo e personagens memoráveis.',
        genero: ['Crime', 'Drama'],
        streaming: 'HBO Max',
        temporadas: 6,
        exibicao: '1999-2007',
        recomended1: 'Breaking Bad',
        recomended2: 'Boardwalk Empire',
        recomended3: 'Peaky Blinders',
    },
    {
        titulo: 'Band of Brothers',
        descricao: 'Minissérie que acompanha a história da Companhia Easy, uma unidade de paraquedistas norte-americanos durante a Segunda Guerra Mundial. A série retrata a camaradagem, o horror da guerra e as transformações dos soldados ao longo do conflito.',
        genero: ['Guerra', 'Drama', 'História'],
        streaming: 'HBO Max',
        temporadas: 1,
        exibicao: '2001',
        recomended1: 'The Pacific',
        recomended2: 'Generation Kill',
        recomended3: 'Saving Private Ryan',
    },
    {
        titulo: 'The Wire',
        descricao: 'Drama policial ambientado em Baltimore, que explora as diversas facetas do tráfico de drogas, da corrupção policial e da vida nas comunidades marginalizadas. A série é conhecida por sua complexidade narrativa e por apresentar personagens ricos e multifacetados.',
        genero: ['Crime', 'Drama'],
        streaming: 'HBO Max',
        temporadas: 5,
        exibicao: '2002-2008',
        recomended1: 'Breaking Bad',
        recomended2: 'Narcos',
        recomended3: 'Top Boy',
    },
    {
        titulo: 'Better Call Saul',
        descricao: 'Pré-sequência de Breaking Bad, que acompanha a transformação de Jimmy McGill em Saul Goodman, o advogado corrupto. A série explora a trajetória de Jimmy antes de conhecer Walter White, revelando os eventos que o levaram a se tornar o advogado mais procurado de Albuquerque.',
        genero: ['Drama', 'Crime'],
        streaming: 'Netflix',
        temporadas: 6,
        exibicao: '2015-2022',
        recomended1: 'Breaking Bad',
        recomended2: 'Mad Men',
        recomended3: 'Fargo',
    },
    {
        titulo: 'Stranger Things',
        descricao: 'Série de ficção científica ambientada nos anos 80, que acompanha um grupo de crianças que investigam o desaparecimento de um amigo e entram em contato com forças sobrenaturais. A série é uma homenagem aos clássicos do cinema e da televisão, com elementos de terror, aventura e drama.',
        genero: ['Ficção Científica', 'Terror', 'Drama'],
        streaming: 'Netflix',
        temporadas: 4,
        exibicao: '2016-presente',
        recomended1: 'Stranger Things',
        recomended2: 'The X-Files',
        recomended3: 'Twin Peaks',
    },
    {
        titulo: 'Sherlock',
        descricao: 'Série de detetive britânica moderna que reinventa o clássico personagem Sherlock Holmes. A série acompanha as aventuras de Sherlock e de seu fiel companheiro, Dr. Watson, enquanto eles desvendam mistérios complexos em Londres.',
        genero: ['Mistério', 'Drama', 'Policial'],
        streaming: 'Netflix',
        temporadas: 4,
        exibicao: '2010-2017',
        recomended1: 'Elementary',
        recomended2: 'Luther',
        recomended3: 'True Detective',
    },
    {
        titulo: 'Peaky Blinders',
        descricao: 'Drama histórico ambientado em Birmingham, Inglaterra, nos anos 1920. A série acompanha a família Shelby, uma gangue que controla a cidade, e seus envolvimentos com o crime organizado, a política e a sociedade da época.',
        genero: ['Crime', 'Drama', 'História'],
        streaming: 'Netflix',
        temporadas: 6,
        exibicao: '2013-2022',
        recomended1: 'Boardwalk Empire',
        recomended2: 'Gangs of London',
        recomended3: 'The Knick',
    },
    {
        titulo: 'The Twilight Zone',
        descricao: 'Antologia de ficção científica que explora temas como a condição humana, a tecnologia e o sobrenatural através de histórias curtas e aterrorizantes. Cada episódio apresenta uma história diferente, com um final inesperado e reflexivo.',
        genero: ['Ficção Científica', 'Terror', 'Drama'],
        streaming: 'Amazon Prime Video',
        temporadas: 5,
        exibicao: '1959-1964',
        recomended1: 'Black Mirror',
        recomended2: 'The Outer Limits',
        recomended3: 'Love, Death & Robots',
    },
    {
        titulo: 'Fleabag',
        descricao: 'Comédia dramática que acompanha a vida de uma mulher jovem e cínica que luta para lidar com a morte de sua melhor amiga e com os desafios da vida adulta. A série é conhecida por seu humor ácido e por sua abordagem honesta e realista sobre questões como a solidão, a ansiedade e as relações interpessoais.',
        genero: ['Comédia', 'Drama'],
        streaming: 'Amazon Prime Video',
        temporadas: 2,
        exibicao: '2016-2019',
        recomended1: 'Killing Eve',
        recomended2: 'Catastrophe',
        recomended3: 'I May Destroy You',
    },
    {
        titulo: 'Fargo',
        descricao: 'Antologia criminal que explora diferentes histórias ambientadas na região de Fargo, nos Estados Unidos. Cada temporada apresenta novos personagens e tramas, mas mantém o estilo noir característico da série, com humor negro, violência e diálogos memoráveis.',
        genero: ['Crime', 'Drama', 'Thriller'],
        streaming: 'Netflix',
        temporadas: 4,
        exibicao: '2014-presente',
        recomended1: 'True Detective',
        recomended2: 'Breaking Bad',
        recomended3: 'The Night Of',
    },
    {
        titulo: 'House',
        descricao: 'Drama médico que acompanha a vida de Gregory House, um médico brilhante e misantropo que lidera uma equipe de diagnósticos em um hospital universitário. A série é conhecida por seus casos médicos complexos e pela personalidade cativante e sarcástica de House.',
        genero: ['Drama', 'Médico'],
        streaming: 'Amazon Prime Video',
        temporadas: 8,
        exibicao: '2004-2012',
        recomended1: 'The Good Doctor',
        recomended2: 'Scrubs',
        recomended3: 'Greys Anatomy',
    },
    {
        titulo: 'Friends',
        descricao: 'Sitcom que acompanha a vida de um grupo de amigos em Nova York. A série é conhecida por seu humor leve e descontraído, por seus personagens carismáticos e por abordar temas do dia a dia de forma divertida e relatable.',
        genero: ['Comédia'],
        streaming: 'HBO Max',
        temporadas: 10,
        exibicao: '1994-2004',
        recomended1: 'How I Met Your Mother',
        recomended2: 'The Big Bang Theory',
        recomended3: 'Seinfeld',
    },
    {
        titulo: 'Dark',
        descricao: 'Série alemã de ficção científica que explora temas como viagem no tempo, destino e as consequências de nossas ações. A trama se desenrola em uma pequena cidade onde uma série de desaparecimentos misteriosos estão conectados por eventos que se repetem ao longo de várias gerações.',
        genero: ['Ficção Científica', 'Drama', 'Mistério'],
        streaming: 'Netflix',
        temporadas: 3,
        exibicao: '2017-2020',
        recomended1: 'Lost',
        recomended2: 'Sense8',
        recomended3: 'Travelers',
    },
    {
        titulo: 'The Office',
        descricao: 'Comédia americana que satiriza a cultura corporativa, acompanhada por uma equipe de funcionários de um escritório de papelaria. A série é conhecida por seu humor irônico e por seus personagens cômicos e memoráveis.',
        genero: ['Comédia'],
        streaming: 'Amazon Prime Video',
        temporadas: 9,
        exibicao: '2005-2013',
        recomended1: 'Parks and Recreation',
        recomended2: 'The IT Crowd',
        recomended3: 'Brooklyn Nine-Nine',
    },
    {
        titulo: 'Succession',
        descricao: 'Drama sobre uma poderosa família bilionária que controla um conglomerado de mídia. A série explora as intrigas familiares, as disputas pelo poder e as consequências das ações de cada membro da família.',
        genero: ['Drama'],
        streaming: 'HBO Max',
        temporadas: 4,
        exibicao: '2018-presente',
        recomended1: 'Billions',
        recomended2: 'The Crown',
        recomended3: 'House of Cards',
    },
    {
        titulo: 'Battlestar Galactica',
        descricao: 'Série de ficção científica que acompanha um grupo de sobreviventes humanos que fogem dos Cylons, uma raça de robôs que exterminou a maior parte da humanidade. A série explora temas como a natureza humana, a fé e a busca por um novo lar.',
        genero: ['Ficção Científica', 'Drama'],
        streaming: 'Amazon Prime Video',
        temporadas: 4,
        exibicao: '2004-2009',
        recomended1: 'The Expanse',
        recomended2: 'Westworld',
        recomended3: 'Raised by Wolves',
    },
    {
        titulo: 'Freaks and Geeks',
        descricao: 'Comédia dramática que retrata a vida de um grupo de adolescentes marginalizados em um colégio americano. A série explora temas como a busca pela identidade, as dificuldades da adolescência e as relações familiares.',
        genero: ['Comédia', 'Drama'],
        streaming: 'Netflix',
        temporadas: 1,
        exibicao: '1999-2000',
        recomended1: 'The End of the F***ing World',
        recomended2: 'Pen15',
        recomended3: 'Euphoria',
    },
    {
        titulo: 'Mad Men',
        descricao: 'Drama ambientado na década de 1960, que acompanha a vida de um grupo de executivos de publicidade em Nova York. A série explora temas como a cultura da época, o machismo, o racismo e as mudanças sociais.',
        genero: ['Drama'],
        streaming: 'Amazon Prime Video',
        temporadas: 7,
        exibicao: '2007-2015',
        recomended1: 'The Americans',
        recomended2: 'Pan Am',
        recomended3: 'Halt and Catch Fire',
    },
    {
        titulo: 'Narcos',
        descricao: 'Série biográfica que retrata a história do tráfico de cocaína na Colômbia, com foco no cartel de Medellín liderado por Pablo Escobar. A série explora a violência, a corrupção e as consequências do narcotráfico para a sociedade colombiana.',
        genero: ['Drama', 'Crime', 'Biografia'],
        streaming: 'Netflix',
        temporadas: 3,
        exibicao: '2015-2017',
        recomended1: 'Narcos: Mexico',
        recomended2: 'El Chapo',
        recomended3: 'ZeroZeroZero',
    },
    {
        titulo: 'Mindhunter',
        descricao: 'Série policial que acompanha dois agentes do FBI que criam um novo método de perfil psicológico para identificar assassinos em série. A série é baseada em fatos reais e explora a mente dos criminosos mais perigosos da história.',
        genero: ['Drama', 'Crime', 'Thriller'],
        streaming: 'Netflix',
        temporadas: 3,
        exibicao: '2017-2019',
        recomended1: 'True Detective',
        recomended2: 'The Silence of the Lambs',
        recomended3: 'Dexter',
    },
    {
        titulo: 'Mr. Robot',
        descricao: 'Thriller psicológico que acompanha um jovem hacker que é recrutado por um grupo de ativistas que busca derrubar as maiores corporações do mundo. A série explora temas como a tecnologia, a paranoia e a identidade.',
        genero: ['Thriller', 'Drama', 'Ficção Científica'],
        streaming: 'Amazon Prime Video',
        temporadas: 4,
        exibicao: '2015-2019',
        recomended1: 'Black Mirror',
        recomended2: 'Utopia',
        recomended3: 'Person of Interest',
    },
    {
        titulo: 'Black Mirror',
        descricao: 'Antologia de ficção científica que explora as consequências da tecnologia na sociedade moderna. Cada episódio apresenta uma história diferente, com um final inesperado e muitas vezes distópico.',
        genero: ['Ficção Científica', 'Drama', 'Thriller'],
        streaming: 'Netflix',
        temporadas: 6,
        exibicao: '2011-presente',
        recomended1: 'The Twilight Zone',
        recomended2: 'Westworld',
        recomended3: 'Love, Death & Robots',
    },
{
        titulo: 'Heartstopper',
        descricao: 'Série britânica de romance adolescente que adapta a graphic novel homônima. A série acompanha o desenvolvimento do relacionamento entre Charlie, um estudante gay, e Nick, um jogador de rugby popular.',
        genero: ['Romance', 'Drama', 'LGBTQ+'],
        streaming: 'Netflix',
        temporadas: 2,
        exibicao: '2022-presente',
        recomended1: 'Love, Simon',
        recomended2: 'Call Me by Your Name',
        recomended3: 'The Fault in Our Stars',
    },
    {
        titulo: 'Severance',
        descricao: 'Série de ficção científica que acompanha um grupo de funcionários de uma empresa que se submete a um procedimento que separa suas memórias profissionais das pessoais. A série explora as consequências desse procedimento e os mistérios que envolvem a empresa.',
        genero: ['Ficção Científica', 'Thriller', 'Drama'],
        streaming: 'Apple TV+',
        temporadas: 2,
        exibicao: '2022-presente',
        recomended1: 'Black Mirror',
        recomended2: 'Westworld',
        recomended3: 'Person of Interest',
    },
    {
        titulo: 'Its Always Sunny in Philadelphia',
        descricao: 'Comédia americana que satiriza a cultura pop e os estereótipos de classe média. A série acompanha um grupo de amigos egoístas e ineptos que administram um bar na Filadélfia.',
        genero: ['Comédia'],
        streaming: 'Hulu',
        temporadas: 16,
        exibicao: '2005-presente',
        recomended1: 'Archer',
        recomended2: 'South Park',
        recomended3: 'Family Guy',
    },
    {
        titulo: 'The Boys',
        descricao: 'Série de super-heróis que satiriza o gênero, mostrando os super-heróis como pessoas corruptas e egoístas. A série acompanha um grupo de vigilantes que se une para combater os super-heróis e a empresa que os controla.',
        genero: ['Super-heróis', 'Drama', 'Comédia'],
        streaming: 'Amazon Prime Video',
        temporadas: 4,
        exibicao: '2019-presente',
        recomended1: 'Invincible',
        recomended2: 'Watchmen',
        recomended3: 'The Umbrella Academy',
    },
    {
        titulo: 'Seinfeld',
        descricao: 'Sitcom clássica que acompanha a vida de quatro amigos em Nova York. A série é conhecida por seu humor observacional e por abordar temas do cotidiano de forma satírica e inteligente.',
        genero: ['Comédia'],
        streaming: 'Netflix',
        temporadas: 9,
        exibicao: '1989-1998',
        recomended1: 'Friends',
        recomended2: 'Seinfeld',
        recomended3: 'Curb Your Enthusiasm',
    },
    {
        titulo: 'Peep Show',
        descricao: 'Comédia britânica que acompanha a vida de dois amigos insegura e mal-ajustados. A série é conhecida por seu humor ácido e por seus personagens cômicos e vergonhosos.',
        genero: ['Comédia'],
        streaming: 'Channel 4',
        temporadas: 9,
        exibicao: '2003-2015',
        recomended1: 'The IT Crowd',
        recomended2: 'Father Ted',
        recomended3: 'Black Books',
    },
    {
        titulo: 'The Last of Us',
        descricao: 'Série pós-apocalíptica baseada no jogo de mesmo nome. A série acompanha Joel, um contrabandista, e Ellie, uma adolescente imune a um vírus mortal, em uma jornada pelos Estados Unidos devastados.',
        genero: ['Ficção Científica', 'Drama', 'Aventura'],
        streaming: 'HBO Max',
        temporadas: 1,
        exibicao: '2023',
        recomended1: 'The Walking Dead',
        recomended2: 'Station Eleven',
        recomended3: 'Left Behind',
    },
    {
        titulo: 'When They See Us',
        descricao: 'Minissérie que retrata o caso Central Park Five, em que cinco jovens negros foram injustamente condenados por um estupro em Nova York. A série explora os temas de racismo, injustiça e a luta pela justiça.',
        genero: ['Drama', 'História'],
        streaming: 'Netflix',
        temporadas: 1,
        exibicao: '2019',
        recomended1: '13th',
        recomended2: 'The Trial of the Chicago 7',
        recomended3: 'The Green Mile',
    },
    {
        titulo: 'The Mandalorian',
        descricao: 'Série de ficção científica ambientada no universo de Star Wars. A série acompanha um caçador de recompensas solitário que se torna o protetor de um bebê Yoda.',
        genero: ['Ficção Científica', 'Aventura'],
        streaming: 'Disney+',
        temporadas: 3,
        exibicao: '2019-presente',
        recomended1: 'The Clone Wars',
        recomended2: 'Rebels',
        recomended3: 'Rogue One: A Star Wars Story',
    },
    {
        titulo: 'Lost',
        descricao: 'Série de ficção científica que acompanha um grupo de sobreviventes de um acidente de avião que ficam ilhados em uma misteriosa ilha tropical. A série explora temas como a natureza humana, a fé e os mistérios da ilha.',
        genero: ['Ficção Científica', 'Drama', 'Mistério'],
        streaming: 'Disney+',
        temporadas: 6,
        exibicao: '2004-2010',
        recomended1: 'Dark',
        recomended2: 'Sense8',
        recomended3: 'The Leftovers',
    },
    {
        titulo: 'Line of Duty',
        descricao: 'Série britânica policial que acompanha uma unidade anti-corrupção da polícia de Belfast. A série explora os temas da corrupção policial, da violência e da justiça.',
        genero: ['Drama', 'Policial'],
        streaming: 'BBC iPlayer',
        temporadas: 7,
        exibicao: '2012-presente',
        recomended1: 'Bodyguard',
        recomended2: 'Broadchurch',
        recomended3: 'Luther',
    },
    {
        titulo: 'Deadwood',
        descricao: 'Série de drama histórico ambientada na cidade de Deadwood, Dakota do Sul, durante a corrida do ouro. A série retrata a violência, a corrupção e a formação da sociedade americana no oeste selvagem.',
        genero: ['Drama', 'História'],
        streaming: 'HBO Max',
        temporadas: 3,
        exibicao: '2004-2006',
        recomended1: 'Westworld',
        recomended2: 'Hell on Wheels',
        recomended3: 'Lonesome Dove',
    },
    {
        titulo: 'Mare of Easttown',
        descricao: 'Minissérie policial que acompanha uma detetive de uma pequena cidade da Pensilvânia que investiga um caso de assassinato. A série explora temas como a violência doméstica, o vício e a vida em uma comunidade rural.',
        genero: ['Drama', 'Policial'],
        streaming: 'HBO Max',
        temporadas: 1,
        exibicao: '2021',
        recomended1: 'True Detective',
        recomended2: 'Big Little Lies',
        recomended3: 'Sharp Objects',
    },
    {
        titulo: 'Hannibal',
        descricao: 'Série de terror psicológico que acompanha a relação entre o psiquiatra Hannibal Lecter e o agente do FBI Will Graham. A série é conhecida por sua violência gráfica, seus personagens complexos e sua atmosfera sombria.',
        genero: ['Terror', 'Drama', 'Thriller'],
        streaming: 'Netflix',
        temporadas: 3,
        exibicao: '2013-2015',
        recomended1: 'The Silence of the Lambs',
        recomended2: 'Dexter',
        recomended3: 'Fargo',
    },
    {
        titulo: 'The Bear',
        descricao: 'Uma série dramática que acompanha a jornada de Carmen "Carmy" Berzatto, um jovem chef talentoso que retorna à sua cidade natal em Chicago para assumir o sanduíche de carne bovina de sua família. Carmy, com sua experiência em restaurantes com estrelas Michelin, precisa lidar com a pressão de manter o negócio familiar e com a equipe desorganizada, enquanto busca encontrar seu lugar e um novo propósito na vida.',
        genero: ['Drama', 'Comédia', 'Culinária'],
        streaming: 'Star+',
        temporadas: 2,
        exibicao: '2022-presente',
        recomended1: 'Chefs Table', 
        recomended2: 'Kitchen Nightmares', 
        recomended3: 'Barry', 
      },
      {
        titulo: 'Boardwalk Empire',
        descricao: 'Ambientada na era do proibicionismo, a série acompanha a ascensão e queda de Enoch "Nucky" Thompson, um poderoso político e contrabandista de bebidas alcoólicas em Atlantic City. Nucky, um homem charmoso e calculista, manipula seus inimigos e aliados para construir um império criminoso, enquanto lida com as consequências de suas escolhas e com a crescente violência da cidade.',
        genero: ['Drama', 'Crime', 'Histórico'],
        streaming: 'HBO Max',
        temporadas: 5,
        exibicao: '2010-2014',
        recomended1: 'Peaky Blinders', 
        recomended2: 'The Knick', 
        recomended3: 'Mad Men', 
      },
      {
        titulo: 'Atlanta',
        descricao: 'Uma comédia dramática que explora a vida de Earn Marks, um jovem universitário que tenta ajudar seu primo, o rapper Paper Boi, a alcançar o sucesso na indústria musical de Atlanta. A série, com um humor peculiar e reflexivo, aborda temas como raça, classe social e a busca por identidade, através de histórias interconectadas e personagens complexos.',
        genero: ['Comédia', 'Drama', 'Musical'],
        streaming: 'Star+',
        temporadas: 4,
        exibicao: '2016-2022',
        recomended1: 'Insecure', 
        recomended2: 'Master of None', 
        recomended3: 'Fleabag', 
      },
      {
        titulo: 'Vikings',
        descricao: 'Uma saga épica que acompanha as aventuras de Ragnar Lothbrok, um ambicioso guerreiro viking que ascende ao poder e lidera seu povo em expedições marítimas e batalhas épicas. A série retrata a vida cotidiana dos vikings, suas crenças, seus conflitos internos e suas jornadas em busca de novas terras e riquezas.',
        genero: ['Ação', 'Drama', 'História'],
        streaming: 'Amazon Prime Video',
        temporadas: 6,
        exibicao: '2013-2020',
        recomended1: 'Game of Thrones',
        recomended2: 'The Last Kingdom',
        recomended3: 'Spartacus',
    },
    {
        titulo: 'Twin Peaks',
        descricao: 'Um mistério envolvente e surreal que se desenrola na pequena cidade de Twin Peaks após o assassinato da popular adolescente Laura Palmer. A série combina elementos de drama policial, horror e suspense psicológico, explorando temas como dualidade, sexualidade e o sobrenatural. A trama se aprofunda em um mundo onírico e intrigante, com personagens complexos e reviravoltas inesperadas.',
        genero: ['Mistério', 'Drama', 'Suspense'],
        streaming: 'HBO Max',
        temporadas: 3,
        exibicao: '1990-1991, 2017',
        recomended1: 'True Detective',
        recomended2: 'Fargo',
        recomended3: 'The X-Files',
    },
    {
        titulo: 'The Shield',
        descricao: 'Um drama policial intenso e controverso que acompanha a vida de Vic Mackey, um detetive corrupto e ambicioso que lidera uma unidade de elite da polícia de Los Angeles. A série explora os limites da lei e da moralidade, mostrando as consequências das ações de Mackey e de sua equipe enquanto eles se envolvem em esquemas criminosos para alcançar seus objetivos. A narrativa é marcada por violência, traição e dilemas éticos.',
        genero: ['Drama', 'Policial', 'Crime'],
        streaming: 'Paramount+',
        temporadas: 7,
        exibicao: '2002-2008',
        recomended1: 'Breaking Bad',
        recomended2: 'Ozark',
        recomended3: 'Narcos',
    },
    {
        titulo: 'Happy Valley',
        descricao: 'Uma detetive durona e experiente investiga uma série de crimes em uma comunidade rural da Inglaterra. A série explora temas como violência doméstica, abuso infantil e a complexidade das relações familiares.',
        genero: ['Drama', 'Policial', 'Suspense'],
        streaming: 'Netflix',
        temporadas: 3,
        exibicao: '2014-2016',
        recomended1: 'Broadchurch',
        recomended2: 'Line of Duty',
        recomended3: 'The Killing',
    },
    {
        titulo: 'True Detective',
        descricao: 'Uma antologia policial que acompanha diferentes detetives investigando casos complexos e sobrenaturais. Cada temporada apresenta uma nova história com personagens e cenários distintos, explorando temas como corrupção, misticismo e a natureza humana.',
        genero: ['Drama', 'Policial', 'Mistério'],
        streaming: 'HBO Max',
        temporadas: 4,
        exibicao: '2014-presente',
        recomended1: 'Fargo',
        recomended2: 'Twin Peaks',
        recomended3: 'Mindhunter',
    },
    {
        titulo: 'The Haunting of Hill House',
        descricao: 'Uma série de terror psicológico que reimagina o clássico romance de Shirley Jackson. A história acompanha uma família que se muda para uma mansão assombrada e enfrenta traumas do passado enquanto são atormentados por forças sobrenaturais.',
        genero: ['Terror', 'Drama', 'Suspense'],
        streaming: 'Netflix',
        temporadas: 1,
        exibicao: 2018,
        recomended1: 'The Haunting of Bly Manor',
        recomended2: 'Midnight Mass',
        recomended3: 'American Horror Story',
    },
    {
        titulo: 'The Americans',
        descricao: 'Um drama de espionagem ambientado durante a Guerra Fria que acompanha dois agentes da KGB que vivem disfarçados como um casal americano suburbano. A série explora os desafios de manter uma identidade secreta, a lealdade e as consequências da Guerra Fria.',
        genero: ['Drama', 'Espionagem', 'Thriller'],
        streaming: 'Amazon Prime Video',
        temporadas: 6,
        exibicao: '2013-2018',
        recomended1: 'The Night Manager',
        recomended2: 'Killing Eve',
        recomended3: 'Homeland',
    },
    {
        titulo: 'Justified',
        descricao: 'Um drama policial ambientado nas montanhas de Kentucky, que acompanha um U.S. Marshal que retorna à sua cidade natal para perseguir um fugitivo. A série combina elementos de western, drama criminal e comédia, explorando temas como justiça, vingança e a cultura do sul dos Estados Unidos.',
        genero: ['Drama', 'Policial', 'Western'],
        streaming: 'Hulu',
        temporadas: 6,
        exibicao: '2010-2015',
        recomended1: 'Breaking Bad',
        recomended2: 'Sons of Anarchy',
        recomended3: 'Fargo',
    },
];

